from picomongo import ConnectionManager

PICOMONGO_CONFIG = {'_default_': {'db': 'FeedLight'}}

TWITTER_APP_TOKEN = "YOUR_TWITTER_APP_TOKEN"
TWITTER_APP_SECRET = "YOUR_TWITTER_APP_SECRET"

FACEBOOK_APP_TOKEN = "YOUR_FACEBOOK_APP_TOKEN"
FACEBOOK_APP_SECRET = "YOUR_FACEBOOK_APP_SECRET"

POCKET_APP_TOKEN = "YOUR_POCKET_APP_TOKEN"

DIFFBOT_APP_TOKEN = "YOUR_DIFFBOT_APP_TOKEN"

INTERCOM_APP_TOKEN = "YOUR_INTERCOM_APP_TOKEN"

FLASK_CONFIG = {
    'SERVER_NAME': 'feedlight.dev:5000',
    'audience': 'http://feedlight.dev:5000'
}

ConnectionManager.configure(PICOMONGO_CONFIG)
